// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Tindarr.Infrastructure.Persistence;

#nullable disable

namespace Tindarr.Infrastructure.Persistence.Migrations;

[DbContext(typeof(TindarrDbContext))]
[Migration("20260214160000_AddCastingSettingsAudioTrackKind")]
public partial class AddCastingSettingsAudioTrackKind
{
}
