// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tindarr.Infrastructure.Persistence;

#nullable disable

namespace Tindarr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TindarrDbContext))]
    [Migration("20260127180627_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");
#pragma warning restore 612, 618
        }
    }
}
